server:
  port: 8081

spring:
  application:
    name: axcmsm
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://master:3306/redis_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: passwd
  redis:
    host: master
    port: 6379
    #password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
  type-aliases-package: com.axcmsm.entity # ?????
logging:
  level:
    com.hmdp: debug

